language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

# Install hugo, lunr (search) & minimo theme (v2.7.0)
install:
  - curl -Lo hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_0.62.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  - npm install lunr glob
  - git clone https://github.com/MunifTanjim/minimo.git --branch v2.7.0 themes/minimo

before_script:
    - rm -rf public 2> /dev/null

# Run the build script
script:
  - hugo

# Need to add post build for the search functionality...
before_deploy:
  - node themes/minimo/scripts/generate-search-index-lunr.js

deploy:
  provider: pages
  local_dir: public
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  verbose: true
  keep-history: true
  on:
    branch: master
